# Generated by Django 5.1.1 on 2024-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessed',
            field=models.BooleanField(default=False),
        ),
    ]
