# Generated by Django 5.1.1 on 2024-09-12 06:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('TN', 'Tank'), ('HE', 'Healer'), ('DD', 'Dd'), ('DL', 'Dealer'), ('GM', 'GuildMaster'), ('QG', 'QuestGiver'), ('BS', 'BlackSmith'), ('TN', 'Tanner'), ('PM', 'PotionMaster'), ('MS', 'MasterSpells')], max_length=15)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
